### ISSUE TITLE
Interface language

### ISSUE THREAD

**Issue by pcav** [ansup0402/KoALA#1]
Hi,
is the interface in Korean only?
Regards, and thanks for sharing.

**Comment by ansup0402** [comment]
yes.. it's korean only..

2019년 11월 2일 (토) 15:55, Paolo Cavallini <notifications@github.com>님이 작성:

**Comment by pcav** [comment]
Thanks for the clarification. Could you please make it translatable, and add the English translation, in order to make your work usable for more people?
I'm personally willing to help with the revision of the translation, if needed.

**Comment by ansup0402** [comment]
In my opinion, "KoALA" still needs to be complemented. Many people use it
in their work and modify it to complement the algorithm. If necessary, I
will consider English service.

By the way, can't I upload the plug-in without English service?

2019년 11월 4일 (월) 오후 4:12, Paolo Cavallini <notifications@github.com>님이 작성:

**Comment by pcav** [comment]
We avoid plugins without an English translation. The few exceptions are for services only available for a specific country, which would not seem the case here. Am I wrong?

**Comment by ansup0402** [comment]
I mean I'm worried that it's going to confuse others with an unproven
algorithm.
Do you mean that in order to upload plugins, the plugin must be written in
English? Right?

2019년 11월 4일 (월) 오후 8:29, Paolo Cavallini <notifications@github.com>님이 작성:

**Comment by pcav** [comment]
It can be written in any language, but it should have its i18n translation file, with a default to English, so those with a non-Korean interface will see the menus in English.
Translation of the menus is usually very quick, I imagine it will be just a few tens of strings.

**Comment by ansup0402** [comment]
I understand ... Thank you. I know what you mean.
Do you have any reference on how to use 'i18n'?
Maybe I should study 'i18n' first.

Thank you for the advice.

2019년 11월 4일 (월) 오후 8:50, Paolo Cavallini <notifications@github.com>님이 작성:

**Comment by pcav** [comment]
Please have a look to our guide:
https://docs.qgis.org/3.4/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#translate-using-makefile
In case you need help, please do not hesitate asking on the qgis-dev mailing list.

**Comment by ansup0402** [comment]
Thank you so much. I'll fix and upload it again.

2019년 11월 4일 (월) 오후 9:02, Paolo Cavallini <notifications@github.com>님이 작성:

**Comment by pcav** [comment]
Thanks for understanding. I'm sure this will bring even more success to your work

**Comment by ansup0402** [comment]
hi paolo

I changed to support English.
If you have time, could you check it out?

thanks a lot..

2019년 11월 4일 (월) 오후 9:13, Paolo Cavallini <notifications@github.com>님이 작성:

**Comment by pcav** [comment]
Tested lightly, published.
Thanks!
